# port
server:
 port: 8080

# datasource
spring:
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/upload?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
#springboot 集成 jsp
 mvc:
  view:
   prefix: WEB-INF/jsp/
   suffix: .jsp
  # 解开拦截，就可以访问静态资源了
  static-path-pattern: /static/**
  # 默认是1MB 配置文件设置 上传文件允许 2MB
 servlet:
  multipart:
   max-file-size: 2MB
   max-request-size: 2MB

# mybatis
mybatis:
# 引入mybatis-config.xml 文件
# config-location: classpath:mybatis-config.xml
 mapper-locations: classpath*:mybatis-mapper/*.xml
 type-aliases-package: com.ganguixu.upload.model
